version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  style_guide = "airbnb"
  plugins = ["react"]
  environment = [
    "browser",
    "nodejs",
    "jest"
  ]
